### ISSUE TITLE
User guide

### ISSUE THREAD

**Issue by Gediz-Aksit** [chkuendig/hass-hp_ilo-beta#1]
Hello, I know this is a beta but I kind of want to try it.

When I try to install the integration, I am greeted by a a textbox. I tried inputting the ILO IP but I get an "unknown error".

Traceback (most recent call last):
  File "/config/custom_components/hp_ilo/config_flow.py", line 120, in async_step_user
    hello = partial(blk.hello, host, timeout=timeout)
                    ^^^
NameError: name 'blk' is not defined

  File "/config/custom_components/hp_ilo/config_flow.py", line 123, in async_step_user
    except NetworkTimeoutError:
           ^^^^^^^^^^^^^^^^^^^
NameError: name 'NetworkTimeoutError' is not defined

**Comment by chkuendig** [comment]
I had a look at it and noticed that I never really implemented the most manual setup path (I only use the autodiscovery config flow).

https://github.com/chkuendig/hass-hp_ilo-beta/commit/a2774ac465e25bc86533b9120f1826bd30d69e34 fixes this but I'm not sure that's all that's required to make it work for you.

**Comment by Gediz-Aksit** [comment]
I am unsure how autodiscovery supposed to work. When I install it, I just saw an empty textbox.

Now it is labelled and I was able to fill them in. I however only have empty integration entries.

Is there something I can do differently?
